# Etapa 1: Build da aplicação Angular
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Etapa 2: Configuração do servidor web Nginx
FROM nginx:alpine
COPY --from=build /app/dist/client-app /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
