version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build: ./ClientApp
    ports:
      - "4200:80"
    depends_on:
      - backend
